CREATE TABLE TEST_EMPLOYEE1 (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(50),
    institute VARCHAR2(100)
);

CREATE TABLE TEST_EMPLOYEE2 (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(50),
    institute VARCHAR2(100)
);
CREATE TABLE TRI2GPS_DEV.TEST_EMPLOYEE1 (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(50),
    institute VARCHAR2(100)
);
CREATE TABLE STATEGPS.TEST_EMPLOYEE (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(50),
    institute VARCHAR2(100)
);
