package oracle.apps.sfc.lcissuance.multi.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.sfc.lcissuance.multi.lov.server.LcReqIdVOImpl;
import oracle.apps.sfc.lcissuance.multi.lov.server.LcReqVendorVOImpl;
import oracle.apps.sfc.lcissuance.multi.lov.server.OrganizationVOImpl;
import oracle.apps.sfc.lcissuance.multi.lov.server.PaymentTermsVOImpl;
import oracle.apps.sfc.lcissuance.multi.lov.server.PoDetailsVOImpl;
import oracle.apps.sfc.lcissuance.multi.lov.server.TradeTermsVOImpl;
import oracle.apps.sfc.lcissuance.multi.lov.server.VendorSiteVOImpl;
import oracle.apps.sfc.lcissuance.multi.lov.server.VendorVOImpl;
import oracle.apps.sfc.lcissuance.multi.poplist.server.CifCatVOImpl;
import oracle.apps.sfc.lcissuance.multi.poplist.server.FobCatVOImpl;
import oracle.apps.sfc.lcissuance.multi.poplist.server.LCIncotermsVOImpl;
import oracle.apps.sfc.lcissuance.multi.poplist.server.LCTypeVOImpl;
import oracle.apps.sfc.lcissuance.multi.poplist.server.PIIncotermsVOImpl;
import oracle.apps.sfc.lcissuance.server.PeriodOfPresentVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LCMultiAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public LCMultiAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("oracle.apps.sfc.lcissuance.multi.server", /* package name */
      "LCMultiAMLocal" /* Configuration Name */);
    }


    /**Container's getter for OrganizationVO
     */
    public OrganizationVOImpl getOrganizationVO() {
        return (OrganizationVOImpl)findViewObject("OrganizationVO");
    }

    /**Container's getter for VendorVO
     */
    public VendorVOImpl getVendorVO() {
        return (VendorVOImpl)findViewObject("VendorVO");
    }

    /**Container's getter for VendorSiteVO
     */
    public VendorSiteVOImpl getVendorSiteVO() {
        return (VendorSiteVOImpl)findViewObject("VendorSiteVO");
    }

    /**Container's getter for TradeTermsVO
     */
    public TradeTermsVOImpl getTradeTermsVO() {
        return (TradeTermsVOImpl)findViewObject("TradeTermsVO");
    }

    /**Container's getter for PaymentTermsVO
     */
    public PaymentTermsVOImpl getPaymentTermsVO() {
        return (PaymentTermsVOImpl)findViewObject("PaymentTermsVO");
    }

    public void removeLines(String rowRef) 
    {
        LCPoDetailsEVORowImpl curRow = (LCPoDetailsEVORowImpl)this.findRowByRef(rowRef);
        curRow.remove();
    }

    /**Container's getter for PeriodOfPresentVO
     */
    public PeriodOfPresentVOImpl getPeriodOfPresentVO() {
        return (PeriodOfPresentVOImpl)findViewObject("PeriodOfPresentVO");
    }

    /**Container's getter for LCInlandReqEVO
     */
    public LCInlandReqEVOImpl getLCInlandReqEVO() {
        return (LCInlandReqEVOImpl)findViewObject("LCInlandReqEVO");
    }

    /**Container's getter for LCImportReqEVO
     */
    public LCImportReqEVOImpl getLCImportReqEVO() {
        return (LCImportReqEVOImpl)findViewObject("LCImportReqEVO");
    }

    /**Container's getter for LCDocDetailsEVO
     */
    public LCDocDetailsEVOImpl getLCDocDetailsEVO() {
        return (LCDocDetailsEVOImpl)findViewObject("LCDocDetailsEVO");
    }

    /**Container's getter for LCApprHistoryEVO
     */
    public LCApprHistoryEVOImpl getLCApprHistoryEVO() {
        return (LCApprHistoryEVOImpl)findViewObject("LCApprHistoryEVO");
    }


    /**Container's getter for LcReqIdVO
     */
    public LcReqIdVOImpl getLcReqIdVO() {
        return (LcReqIdVOImpl)findViewObject("LcReqIdVO");
    }

    /**Container's getter for LcReqVendorVO
     */
    public LcReqVendorVOImpl getLcReqVendorVO() {
        return (LcReqVendorVOImpl)findViewObject("LcReqVendorVO");
    }


    /**Container's getter for PoDetailsVO
     */
    public PoDetailsVOImpl getPoDetailsVO() {
        return (PoDetailsVOImpl)findViewObject("PoDetailsVO");
    }


    /**Container's getter for LCPoDetailsEVO
     */
    public LCPoDetailsEVOImpl getLCPoDetailsEVO() {
        return (LCPoDetailsEVOImpl)findViewObject("LCPoDetailsEVO");
    }

    /**Container's getter for LCIncotermsVO
     */
    public LCIncotermsVOImpl getLCIncotermsVO() {
        return (LCIncotermsVOImpl)findViewObject("LCIncotermsVO");
    }

    /**Container's getter for PIIncotermsVO
     */
    public PIIncotermsVOImpl getPIIncotermsVO() {
        return (PIIncotermsVOImpl)findViewObject("PIIncotermsVO");
    }


    /**Container's getter for LCValueVO
     */
    public LCValueVOImpl getLCValueVO() {
        return (LCValueVOImpl)findViewObject("LCValueVO");
    }

    /**Container's getter for LCRevHistVO
     */
    public LCRevHistVOImpl getLCRevHistVO() {
        return (LCRevHistVOImpl)findViewObject("LCRevHistVO");
    }


    /**Container's getter for LCApprHistoryRevVO
     */
    public LCApprHistoryRevVOImpl getLCApprHistoryRevVO() {
        return (LCApprHistoryRevVOImpl)findViewObject("LCApprHistoryRevVO");
    }

    /**Container's getter for LCDocDetailsRevVO
     */
    public LCDocDetailsRevVOImpl getLCDocDetailsRevVO() {
        return (LCDocDetailsRevVOImpl)findViewObject("LCDocDetailsRevVO");
    }

    /**Container's getter for LCPoDetailsRevVO
     */
    public LCPoDetailsRevVOImpl getLCPoDetailsRevVO() {
        return (LCPoDetailsRevVOImpl)findViewObject("LCPoDetailsRevVO");
    }


    /**Container's getter for LCTypeVO
     */
    public LCTypeVOImpl getLCTypeVO() {
        return (LCTypeVOImpl)findViewObject("LCTypeVO");
    }

    /**Container's getter for CifCatVO
     */
    public CifCatVOImpl getCifCatVO() {
        return (CifCatVOImpl)findViewObject("CifCatVO");
    }

    /**Container's getter for FobCatVO
     */
    public FobCatVOImpl getFobCatVO() {
        return (FobCatVOImpl)findViewObject("FobCatVO");
    }

    /**Container's getter for TransientVO
     */
    public TransientVOImpl getTransientVO() {
        return (TransientVOImpl)findViewObject("TransientVO");
    }

    /**Container's getter for LCRequestHdrEVO
     */
    public LCRequestHdrEVOImpl getLCRequestHdrEVO() {
        return (LCRequestHdrEVOImpl)findViewObject("LCRequestHdrEVO");
    }

    /**Container's getter for LCReportEVO
     */
    public LCReportEVOImpl getLCReportEVO() {
        return (LCReportEVOImpl)findViewObject("LCReportEVO");
    }

    /**Container's getter for LCRequestHdrRevVO
     */
    public LCRequestHdrRevVOImpl getLCRequestHdrRevVO() {
        return (LCRequestHdrRevVOImpl)findViewObject("LCRequestHdrRevVO");
    }
}
