package oracle.apps.sfc.lcissuance.multi.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LCRequestHdrRevVORowImpl extends OAViewRowImpl {
    public static final int ROWID1 = 0;
    public static final int LCREQUESTID = 1;
    public static final int LCORGID = 2;
    public static final int LCORGNAME = 3;
    public static final int VENDORID = 4;
    public static final int VENDORNAME = 5;
    public static final int VENDORSITEID = 6;
    public static final int VENDORADDRESS = 7;
    public static final int LCCURRENCYCODE = 8;
    public static final int LCVALUE = 9;
    public static final int LCCLASSIFICATION = 10;
    public static final int LCSTATUS = 11;
    public static final int LCDATE = 12;
    public static final int TOTALPOVALUE = 13;
    public static final int BANKID = 14;
    public static final int BANKNAME = 15;
    public static final int BANKADDRESS = 16;
    public static final int BANKIFSCSWIFTCODE = 17;
    public static final int BANKIBAN = 18;
    public static final int LCPARTIALSHIPMENT = 19;
    public static final int LCTRANSHIPMENT = 20;
    public static final int LCMODEOFTRANSPORT = 21;
    public static final int LCPERIODOFDOCUMENT = 22;
    public static final int LCCOUNTRYOFORIGIN = 23;
    public static final int LCCOUNTRYEXPIRE = 24;
    public static final int LCLASTDATEOFSHIPMENT = 25;
    public static final int LCEXPIRYDATE = 26;
    public static final int LCPORTOFDISCHARGE = 27;
    public static final int LCPORTOFLOADING = 28;
    public static final int LCPAYMENTTERMS = 29;
    public static final int LCTRADETERMS = 30;
    public static final int LCPAGEPOMODE = 31;
    public static final int TREASURYCOMMENTS = 32;
    public static final int SUPPLIERCOMMENTS = 33;
    public static final int COMMHEADCOMMENTS = 34;
    public static final int ORIGINALLCNO = 35;
    public static final int ATTRIBUTECATEGORY = 36;
    public static final int ATTRIBUTE1 = 37;
    public static final int ATTRIBUTE2 = 38;
    public static final int ATTRIBUTE3 = 39;
    public static final int ATTRIBUTE4 = 40;
    public static final int ATTRIBUTE5 = 41;
    public static final int ATTRIBUTE6 = 42;
    public static final int ATTRIBUTE7 = 43;
    public static final int ATTRIBUTE8 = 44;
    public static final int ATTRIBUTE9 = 45;
    public static final int ATTRIBUTE10 = 46;
    public static final int ATTRIBUTE11 = 47;
    public static final int ATTRIBUTE12 = 48;
    public static final int ATTRIBUTE13 = 49;
    public static final int ATTRIBUTE14 = 50;
    public static final int ATTRIBUTE15 = 51;
    public static final int ATTRIBUTE16 = 52;
    public static final int ATTRIBUTE17 = 53;
    public static final int ATTRIBUTE18 = 54;
    public static final int ATTRIBUTE19 = 55;
    public static final int ATTRIBUTE20 = 56;
    public static final int ATTRIBUTE21 = 57;
    public static final int ATTRIBUTE22 = 58;
    public static final int ATTRIBUTE23 = 59;
    public static final int ATTRIBUTE24 = 60;
    public static final int ATTRIBUTE25 = 61;
    public static final int CREATIONDATE = 62;
    public static final int CREATEDBY = 63;
    public static final int LASTUPDATEDATE = 64;
    public static final int LASTUPDATEDBY = 65;
    public static final int LASTUPDATELOGIN = 66;
    public static final int VENDORSITECODE = 67;
    public static final int LCVALUEWORDS = 68;
    public static final int FLOWSTATUS = 69;
    public static final int PENDINGWITH = 70;
    public static final int RNSWITCHER = 71;
    public static final int UPDATESWITCHER = 72;
    public static final int WFITEMKEY = 73;
    public static final int DESCOFGOODS = 74;
    public static final int LASTDATEOFSHIPPI = 75;
    public static final int TYPEOFLC = 76;
    public static final int FINANCECOMMENTS = 77;
    public static final int LCINCOTERM = 78;
    public static final int PIINCOTERM = 79;
    public static final int AMENDSWITCHER = 80;
    public static final int SNO = 81;
    public static final int WFKEY = 82;
    public static final int SETREN = 83;
    public static final int RENFOB = 84;
    public static final int RENCIF = 85;
    public static final int PIRENFOB = 86;
    public static final int PIRENCIF = 87;

    /**This is the default constructor (do not remove)
     */
    public LCRequestHdrRevVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RowId1
     */
    public RowID getRowId1() {
        return (RowID) getAttributeInternal(ROWID1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RowId1
     */
    public void setRowId1(RowID value) {
        setAttributeInternal(ROWID1, value);
    }

    /**Gets the attribute value for the calculated attribute LcRequestId
     */
    public Number getLcRequestId() {
        return (Number) getAttributeInternal(LCREQUESTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcRequestId
     */
    public void setLcRequestId(Number value) {
        setAttributeInternal(LCREQUESTID, value);
    }

    /**Gets the attribute value for the calculated attribute LcOrgId
     */
    public Number getLcOrgId() {
        return (Number) getAttributeInternal(LCORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcOrgId
     */
    public void setLcOrgId(Number value) {
        setAttributeInternal(LCORGID, value);
    }

    /**Gets the attribute value for the calculated attribute LcOrgName
     */
    public String getLcOrgName() {
        return (String) getAttributeInternal(LCORGNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcOrgName
     */
    public void setLcOrgName(String value) {
        setAttributeInternal(LCORGNAME, value);
    }

    /**Gets the attribute value for the calculated attribute VendorId
     */
    public Number getVendorId() {
        return (Number) getAttributeInternal(VENDORID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**Gets the attribute value for the calculated attribute VendorName
     */
    public String getVendorName() {
        return (String) getAttributeInternal(VENDORNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorName
     */
    public void setVendorName(String value) {
        setAttributeInternal(VENDORNAME, value);
    }

    /**Gets the attribute value for the calculated attribute VendorSiteId
     */
    public Number getVendorSiteId() {
        return (Number) getAttributeInternal(VENDORSITEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteId
     */
    public void setVendorSiteId(Number value) {
        setAttributeInternal(VENDORSITEID, value);
    }

    /**Gets the attribute value for the calculated attribute VendorAddress
     */
    public String getVendorAddress() {
        return (String) getAttributeInternal(VENDORADDRESS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorAddress
     */
    public void setVendorAddress(String value) {
        setAttributeInternal(VENDORADDRESS, value);
    }

    /**Gets the attribute value for the calculated attribute LcCurrencyCode
     */
    public String getLcCurrencyCode() {
        return (String) getAttributeInternal(LCCURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcCurrencyCode
     */
    public void setLcCurrencyCode(String value) {
        setAttributeInternal(LCCURRENCYCODE, value);
    }

    /**Gets the attribute value for the calculated attribute LcValue
     */
    public Number getLcValue() {
        return (Number) getAttributeInternal(LCVALUE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcValue
     */
    public void setLcValue(Number value) {
        setAttributeInternal(LCVALUE, value);
    }

    /**Gets the attribute value for the calculated attribute LcClassification
     */
    public String getLcClassification() {
        return (String) getAttributeInternal(LCCLASSIFICATION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcClassification
     */
    public void setLcClassification(String value) {
        setAttributeInternal(LCCLASSIFICATION, value);
    }

    /**Gets the attribute value for the calculated attribute LcStatus
     */
    public String getLcStatus() {
        return (String) getAttributeInternal(LCSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcStatus
     */
    public void setLcStatus(String value) {
        setAttributeInternal(LCSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute LcDate
     */
    public Date getLcDate() {
        return (Date) getAttributeInternal(LCDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcDate
     */
    public void setLcDate(Date value) {
        setAttributeInternal(LCDATE, value);
    }

    /**Gets the attribute value for the calculated attribute TotalPoValue
     */
    public Number getTotalPoValue() {
        return (Number) getAttributeInternal(TOTALPOVALUE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TotalPoValue
     */
    public void setTotalPoValue(Number value) {
        setAttributeInternal(TOTALPOVALUE, value);
    }

    /**Gets the attribute value for the calculated attribute BankId
     */
    public Number getBankId() {
        return (Number) getAttributeInternal(BANKID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BankId
     */
    public void setBankId(Number value) {
        setAttributeInternal(BANKID, value);
    }

    /**Gets the attribute value for the calculated attribute BankName
     */
    public String getBankName() {
        return (String) getAttributeInternal(BANKNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BankName
     */
    public void setBankName(String value) {
        setAttributeInternal(BANKNAME, value);
    }

    /**Gets the attribute value for the calculated attribute BankAddress
     */
    public String getBankAddress() {
        return (String) getAttributeInternal(BANKADDRESS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BankAddress
     */
    public void setBankAddress(String value) {
        setAttributeInternal(BANKADDRESS, value);
    }

    /**Gets the attribute value for the calculated attribute BankIfscSwiftCode
     */
    public String getBankIfscSwiftCode() {
        return (String) getAttributeInternal(BANKIFSCSWIFTCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BankIfscSwiftCode
     */
    public void setBankIfscSwiftCode(String value) {
        setAttributeInternal(BANKIFSCSWIFTCODE, value);
    }

    /**Gets the attribute value for the calculated attribute BankIban
     */
    public String getBankIban() {
        return (String) getAttributeInternal(BANKIBAN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BankIban
     */
    public void setBankIban(String value) {
        setAttributeInternal(BANKIBAN, value);
    }

    /**Gets the attribute value for the calculated attribute LcPartialShipment
     */
    public String getLcPartialShipment() {
        return (String) getAttributeInternal(LCPARTIALSHIPMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcPartialShipment
     */
    public void setLcPartialShipment(String value) {
        setAttributeInternal(LCPARTIALSHIPMENT, value);
    }

    /**Gets the attribute value for the calculated attribute LcTranshipment
     */
    public String getLcTranshipment() {
        return (String) getAttributeInternal(LCTRANSHIPMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcTranshipment
     */
    public void setLcTranshipment(String value) {
        setAttributeInternal(LCTRANSHIPMENT, value);
    }

    /**Gets the attribute value for the calculated attribute LcModeOfTransport
     */
    public String getLcModeOfTransport() {
        return (String) getAttributeInternal(LCMODEOFTRANSPORT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcModeOfTransport
     */
    public void setLcModeOfTransport(String value) {
        setAttributeInternal(LCMODEOFTRANSPORT, value);
    }

    /**Gets the attribute value for the calculated attribute LcPeriodOfDocument
     */
    public String getLcPeriodOfDocument() {
        return (String) getAttributeInternal(LCPERIODOFDOCUMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcPeriodOfDocument
     */
    public void setLcPeriodOfDocument(String value) {
        setAttributeInternal(LCPERIODOFDOCUMENT, value);
    }

    /**Gets the attribute value for the calculated attribute LcCountryOfOrigin
     */
    public String getLcCountryOfOrigin() {
        return (String) getAttributeInternal(LCCOUNTRYOFORIGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcCountryOfOrigin
     */
    public void setLcCountryOfOrigin(String value) {
        setAttributeInternal(LCCOUNTRYOFORIGIN, value);
    }

    /**Gets the attribute value for the calculated attribute LcCountryExpire
     */
    public String getLcCountryExpire() {
        return (String) getAttributeInternal(LCCOUNTRYEXPIRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcCountryExpire
     */
    public void setLcCountryExpire(String value) {
        setAttributeInternal(LCCOUNTRYEXPIRE, value);
    }

    /**Gets the attribute value for the calculated attribute LcLastDateOfShipment
     */
    public Date getLcLastDateOfShipment() {
        return (Date) getAttributeInternal(LCLASTDATEOFSHIPMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcLastDateOfShipment
     */
    public void setLcLastDateOfShipment(Date value) {
        setAttributeInternal(LCLASTDATEOFSHIPMENT, value);
    }

    /**Gets the attribute value for the calculated attribute LcExpiryDate
     */
    public Date getLcExpiryDate() {
        return (Date) getAttributeInternal(LCEXPIRYDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcExpiryDate
     */
    public void setLcExpiryDate(Date value) {
        setAttributeInternal(LCEXPIRYDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LcPortOfDischarge
     */
    public String getLcPortOfDischarge() {
        return (String) getAttributeInternal(LCPORTOFDISCHARGE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcPortOfDischarge
     */
    public void setLcPortOfDischarge(String value) {
        setAttributeInternal(LCPORTOFDISCHARGE, value);
    }

    /**Gets the attribute value for the calculated attribute LcPortOfLoading
     */
    public String getLcPortOfLoading() {
        return (String) getAttributeInternal(LCPORTOFLOADING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcPortOfLoading
     */
    public void setLcPortOfLoading(String value) {
        setAttributeInternal(LCPORTOFLOADING, value);
    }

    /**Gets the attribute value for the calculated attribute LcPaymentTerms
     */
    public String getLcPaymentTerms() {
        return (String) getAttributeInternal(LCPAYMENTTERMS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcPaymentTerms
     */
    public void setLcPaymentTerms(String value) {
        setAttributeInternal(LCPAYMENTTERMS, value);
    }

    /**Gets the attribute value for the calculated attribute LcTradeTerms
     */
    public String getLcTradeTerms() {
        return (String) getAttributeInternal(LCTRADETERMS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcTradeTerms
     */
    public void setLcTradeTerms(String value) {
        setAttributeInternal(LCTRADETERMS, value);
    }

    /**Gets the attribute value for the calculated attribute LcPagePoMode
     */
    public String getLcPagePoMode() {
        return (String) getAttributeInternal(LCPAGEPOMODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcPagePoMode
     */
    public void setLcPagePoMode(String value) {
        setAttributeInternal(LCPAGEPOMODE, value);
    }

    /**Gets the attribute value for the calculated attribute TreasuryComments
     */
    public String getTreasuryComments() {
        return (String) getAttributeInternal(TREASURYCOMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TreasuryComments
     */
    public void setTreasuryComments(String value) {
        setAttributeInternal(TREASURYCOMMENTS, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierComments
     */
    public String getSupplierComments() {
        return (String) getAttributeInternal(SUPPLIERCOMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierComments
     */
    public void setSupplierComments(String value) {
        setAttributeInternal(SUPPLIERCOMMENTS, value);
    }

    /**Gets the attribute value for the calculated attribute CommheadComments
     */
    public String getCommheadComments() {
        return (String) getAttributeInternal(COMMHEADCOMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CommheadComments
     */
    public void setCommheadComments(String value) {
        setAttributeInternal(COMMHEADCOMMENTS, value);
    }

    /**Gets the attribute value for the calculated attribute OriginalLcNo
     */
    public String getOriginalLcNo() {
        return (String) getAttributeInternal(ORIGINALLCNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OriginalLcNo
     */
    public void setOriginalLcNo(String value) {
        setAttributeInternal(ORIGINALLCNO, value);
    }

    /**Gets the attribute value for the calculated attribute AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute21
     */
    public String getAttribute21() {
        return (String) getAttributeInternal(ATTRIBUTE21);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute22
     */
    public String getAttribute22() {
        return (String) getAttributeInternal(ATTRIBUTE22);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute23
     */
    public String getAttribute23() {
        return (String) getAttributeInternal(ATTRIBUTE23);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute24
     */
    public String getAttribute24() {
        return (String) getAttributeInternal(ATTRIBUTE24);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute25
     */
    public String getAttribute25() {
        return (String) getAttributeInternal(ATTRIBUTE25);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute VendorSiteCode
     */
    public String getVendorSiteCode() {
        return (String) getAttributeInternal(VENDORSITECODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteCode
     */
    public void setVendorSiteCode(String value) {
        setAttributeInternal(VENDORSITECODE, value);
    }

    /**Gets the attribute value for the calculated attribute LcValueWords
     */
    public String getLcValueWords() {
        return (String) getAttributeInternal(LCVALUEWORDS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcValueWords
     */
    public void setLcValueWords(String value) {
        setAttributeInternal(LCVALUEWORDS, value);
    }

    /**Gets the attribute value for the calculated attribute FlowStatus
     */
    public String getFlowStatus() {
        return (String) getAttributeInternal(FLOWSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FlowStatus
     */
    public void setFlowStatus(String value) {
        setAttributeInternal(FLOWSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute PendingWith
     */
    public String getPendingWith() {
        return (String) getAttributeInternal(PENDINGWITH);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PendingWith
     */
    public void setPendingWith(String value) {
        setAttributeInternal(PENDINGWITH, value);
    }

    /**Gets the attribute value for the calculated attribute RnSwitcher
     */
    public String getRnSwitcher() {
        return (String) getAttributeInternal(RNSWITCHER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RnSwitcher
     */
    public void setRnSwitcher(String value) {
        setAttributeInternal(RNSWITCHER, value);
    }

    /**Gets the attribute value for the calculated attribute UpdateSwitcher
     */
    public String getUpdateSwitcher() {
        return (String) getAttributeInternal(UPDATESWITCHER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UpdateSwitcher
     */
    public void setUpdateSwitcher(String value) {
        setAttributeInternal(UPDATESWITCHER, value);
    }

    /**Gets the attribute value for the calculated attribute WfItemKey
     */
    public String getWfItemKey() {
        return (String) getAttributeInternal(WFITEMKEY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WfItemKey
     */
    public void setWfItemKey(String value) {
        setAttributeInternal(WFITEMKEY, value);
    }

    /**Gets the attribute value for the calculated attribute DescOfGoods
     */
    public String getDescOfGoods() {
        return (String) getAttributeInternal(DESCOFGOODS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DescOfGoods
     */
    public void setDescOfGoods(String value) {
        setAttributeInternal(DESCOFGOODS, value);
    }

    /**Gets the attribute value for the calculated attribute LastDateOfShipPi
     */
    public Date getLastDateOfShipPi() {
        return (Date) getAttributeInternal(LASTDATEOFSHIPPI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastDateOfShipPi
     */
    public void setLastDateOfShipPi(Date value) {
        setAttributeInternal(LASTDATEOFSHIPPI, value);
    }

    /**Gets the attribute value for the calculated attribute TypeOfLc
     */
    public String getTypeOfLc() {
        return (String) getAttributeInternal(TYPEOFLC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypeOfLc
     */
    public void setTypeOfLc(String value) {
        setAttributeInternal(TYPEOFLC, value);
    }

    /**Gets the attribute value for the calculated attribute FinanceComments
     */
    public String getFinanceComments() {
        return (String) getAttributeInternal(FINANCECOMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FinanceComments
     */
    public void setFinanceComments(String value) {
        setAttributeInternal(FINANCECOMMENTS, value);
    }

    /**Gets the attribute value for the calculated attribute Lcincoterm
     */
    public String getLcincoterm() {
        return (String) getAttributeInternal(LCINCOTERM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Lcincoterm
     */
    public void setLcincoterm(String value) {
        setAttributeInternal(LCINCOTERM, value);
    }

    /**Gets the attribute value for the calculated attribute Piincoterm
     */
    public String getPiincoterm() {
        return (String) getAttributeInternal(PIINCOTERM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Piincoterm
     */
    public void setPiincoterm(String value) {
        setAttributeInternal(PIINCOTERM, value);
    }

    /**Gets the attribute value for the calculated attribute AmendSwitcher
     */
    public String getAmendSwitcher() {
        return (String) getAttributeInternal(AMENDSWITCHER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AmendSwitcher
     */
    public void setAmendSwitcher(String value) {
        setAttributeInternal(AMENDSWITCHER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            return getRowId1();
        case LCREQUESTID:
            return getLcRequestId();
        case LCORGID:
            return getLcOrgId();
        case LCORGNAME:
            return getLcOrgName();
        case VENDORID:
            return getVendorId();
        case VENDORNAME:
            return getVendorName();
        case VENDORSITEID:
            return getVendorSiteId();
        case VENDORADDRESS:
            return getVendorAddress();
        case LCCURRENCYCODE:
            return getLcCurrencyCode();
        case LCVALUE:
            return getLcValue();
        case LCCLASSIFICATION:
            return getLcClassification();
        case LCSTATUS:
            return getLcStatus();
        case LCDATE:
            return getLcDate();
        case TOTALPOVALUE:
            return getTotalPoValue();
        case BANKID:
            return getBankId();
        case BANKNAME:
            return getBankName();
        case BANKADDRESS:
            return getBankAddress();
        case BANKIFSCSWIFTCODE:
            return getBankIfscSwiftCode();
        case BANKIBAN:
            return getBankIban();
        case LCPARTIALSHIPMENT:
            return getLcPartialShipment();
        case LCTRANSHIPMENT:
            return getLcTranshipment();
        case LCMODEOFTRANSPORT:
            return getLcModeOfTransport();
        case LCPERIODOFDOCUMENT:
            return getLcPeriodOfDocument();
        case LCCOUNTRYOFORIGIN:
            return getLcCountryOfOrigin();
        case LCCOUNTRYEXPIRE:
            return getLcCountryExpire();
        case LCLASTDATEOFSHIPMENT:
            return getLcLastDateOfShipment();
        case LCEXPIRYDATE:
            return getLcExpiryDate();
        case LCPORTOFDISCHARGE:
            return getLcPortOfDischarge();
        case LCPORTOFLOADING:
            return getLcPortOfLoading();
        case LCPAYMENTTERMS:
            return getLcPaymentTerms();
        case LCTRADETERMS:
            return getLcTradeTerms();
        case LCPAGEPOMODE:
            return getLcPagePoMode();
        case TREASURYCOMMENTS:
            return getTreasuryComments();
        case SUPPLIERCOMMENTS:
            return getSupplierComments();
        case COMMHEADCOMMENTS:
            return getCommheadComments();
        case ORIGINALLCNO:
            return getOriginalLcNo();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case ATTRIBUTE11:
            return getAttribute11();
        case ATTRIBUTE12:
            return getAttribute12();
        case ATTRIBUTE13:
            return getAttribute13();
        case ATTRIBUTE14:
            return getAttribute14();
        case ATTRIBUTE15:
            return getAttribute15();
        case ATTRIBUTE16:
            return getAttribute16();
        case ATTRIBUTE17:
            return getAttribute17();
        case ATTRIBUTE18:
            return getAttribute18();
        case ATTRIBUTE19:
            return getAttribute19();
        case ATTRIBUTE20:
            return getAttribute20();
        case ATTRIBUTE21:
            return getAttribute21();
        case ATTRIBUTE22:
            return getAttribute22();
        case ATTRIBUTE23:
            return getAttribute23();
        case ATTRIBUTE24:
            return getAttribute24();
        case ATTRIBUTE25:
            return getAttribute25();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case VENDORSITECODE:
            return getVendorSiteCode();
        case LCVALUEWORDS:
            return getLcValueWords();
        case FLOWSTATUS:
            return getFlowStatus();
        case PENDINGWITH:
            return getPendingWith();
        case RNSWITCHER:
            return getRnSwitcher();
        case UPDATESWITCHER:
            return getUpdateSwitcher();
        case WFITEMKEY:
            return getWfItemKey();
        case DESCOFGOODS:
            return getDescOfGoods();
        case LASTDATEOFSHIPPI:
            return getLastDateOfShipPi();
        case TYPEOFLC:
            return getTypeOfLc();
        case FINANCECOMMENTS:
            return getFinanceComments();
        case LCINCOTERM:
            return getLcincoterm();
        case PIINCOTERM:
            return getPiincoterm();
        case AMENDSWITCHER:
            return getAmendSwitcher();
        case SNO:
            return getSno();
        case WFKEY:
            return getWfKey();
        case SETREN:
            return getSetRen();
        case RENFOB:
            return getRenFob();
        case RENCIF:
            return getRenCif();
        case PIRENFOB:
            return getPIRenFob();
        case PIRENCIF:
            return getPIRenCif();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            setRowId1((RowID)value);
            return;
        case LCREQUESTID:
            setLcRequestId((Number)value);
            return;
        case LCORGID:
            setLcOrgId((Number)value);
            return;
        case LCORGNAME:
            setLcOrgName((String)value);
            return;
        case VENDORID:
            setVendorId((Number)value);
            return;
        case VENDORNAME:
            setVendorName((String)value);
            return;
        case VENDORSITEID:
            setVendorSiteId((Number)value);
            return;
        case VENDORADDRESS:
            setVendorAddress((String)value);
            return;
        case LCCURRENCYCODE:
            setLcCurrencyCode((String)value);
            return;
        case LCVALUE:
            setLcValue((Number)value);
            return;
        case LCCLASSIFICATION:
            setLcClassification((String)value);
            return;
        case LCSTATUS:
            setLcStatus((String)value);
            return;
        case LCDATE:
            setLcDate((Date)value);
            return;
        case TOTALPOVALUE:
            setTotalPoValue((Number)value);
            return;
        case BANKID:
            setBankId((Number)value);
            return;
        case BANKNAME:
            setBankName((String)value);
            return;
        case BANKADDRESS:
            setBankAddress((String)value);
            return;
        case BANKIFSCSWIFTCODE:
            setBankIfscSwiftCode((String)value);
            return;
        case BANKIBAN:
            setBankIban((String)value);
            return;
        case LCPARTIALSHIPMENT:
            setLcPartialShipment((String)value);
            return;
        case LCTRANSHIPMENT:
            setLcTranshipment((String)value);
            return;
        case LCMODEOFTRANSPORT:
            setLcModeOfTransport((String)value);
            return;
        case LCPERIODOFDOCUMENT:
            setLcPeriodOfDocument((String)value);
            return;
        case LCCOUNTRYOFORIGIN:
            setLcCountryOfOrigin((String)value);
            return;
        case LCCOUNTRYEXPIRE:
            setLcCountryExpire((String)value);
            return;
        case LCLASTDATEOFSHIPMENT:
            setLcLastDateOfShipment((Date)value);
            return;
        case LCEXPIRYDATE:
            setLcExpiryDate((Date)value);
            return;
        case LCPORTOFDISCHARGE:
            setLcPortOfDischarge((String)value);
            return;
        case LCPORTOFLOADING:
            setLcPortOfLoading((String)value);
            return;
        case LCPAYMENTTERMS:
            setLcPaymentTerms((String)value);
            return;
        case LCTRADETERMS:
            setLcTradeTerms((String)value);
            return;
        case LCPAGEPOMODE:
            setLcPagePoMode((String)value);
            return;
        case TREASURYCOMMENTS:
            setTreasuryComments((String)value);
            return;
        case SUPPLIERCOMMENTS:
            setSupplierComments((String)value);
            return;
        case COMMHEADCOMMENTS:
            setCommheadComments((String)value);
            return;
        case ORIGINALLCNO:
            setOriginalLcNo((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case ATTRIBUTE11:
            setAttribute11((String)value);
            return;
        case ATTRIBUTE12:
            setAttribute12((String)value);
            return;
        case ATTRIBUTE13:
            setAttribute13((String)value);
            return;
        case ATTRIBUTE14:
            setAttribute14((String)value);
            return;
        case ATTRIBUTE15:
            setAttribute15((String)value);
            return;
        case ATTRIBUTE16:
            setAttribute16((String)value);
            return;
        case ATTRIBUTE17:
            setAttribute17((String)value);
            return;
        case ATTRIBUTE18:
            setAttribute18((String)value);
            return;
        case ATTRIBUTE19:
            setAttribute19((String)value);
            return;
        case ATTRIBUTE20:
            setAttribute20((String)value);
            return;
        case ATTRIBUTE21:
            setAttribute21((String)value);
            return;
        case ATTRIBUTE22:
            setAttribute22((String)value);
            return;
        case ATTRIBUTE23:
            setAttribute23((String)value);
            return;
        case ATTRIBUTE24:
            setAttribute24((String)value);
            return;
        case ATTRIBUTE25:
            setAttribute25((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case VENDORSITECODE:
            setVendorSiteCode((String)value);
            return;
        case LCVALUEWORDS:
            setLcValueWords((String)value);
            return;
        case FLOWSTATUS:
            setFlowStatus((String)value);
            return;
        case PENDINGWITH:
            setPendingWith((String)value);
            return;
        case RNSWITCHER:
            setRnSwitcher((String)value);
            return;
        case UPDATESWITCHER:
            setUpdateSwitcher((String)value);
            return;
        case WFITEMKEY:
            setWfItemKey((String)value);
            return;
        case DESCOFGOODS:
            setDescOfGoods((String)value);
            return;
        case LASTDATEOFSHIPPI:
            setLastDateOfShipPi((Date)value);
            return;
        case TYPEOFLC:
            setTypeOfLc((String)value);
            return;
        case FINANCECOMMENTS:
            setFinanceComments((String)value);
            return;
        case LCINCOTERM:
            setLcincoterm((String)value);
            return;
        case PIINCOTERM:
            setPiincoterm((String)value);
            return;
        case AMENDSWITCHER:
            setAmendSwitcher((String)value);
            return;
        case SNO:
            setSno((Number)value);
            return;
        case WFKEY:
            setWfKey((String)value);
            return;
        case SETREN:
            setSetRen((Boolean)value);
            return;
        case RENFOB:
            setRenFob((Boolean)value);
            return;
        case RENCIF:
            setRenCif((Boolean)value);
            return;
        case PIRENFOB:
            setPIRenFob((Boolean)value);
            return;
        case PIRENCIF:
            setPIRenCif((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Sno
     */
    public Number getSno() {
        return (Number) getAttributeInternal(SNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sno
     */
    public void setSno(Number value) {
        setAttributeInternal(SNO, value);
    }

    /**Gets the attribute value for the calculated attribute WfKey
     */
    public String getWfKey() {
        return (String) getAttributeInternal(WFKEY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WfKey
     */
    public void setWfKey(String value) {
        setAttributeInternal(WFKEY, value);
    }

    /**Gets the attribute value for the calculated attribute SetRen
     */
    public Boolean getSetRen() {
        return (Boolean) getAttributeInternal(SETREN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SetRen
     */
    public void setSetRen(Boolean value) {
        setAttributeInternal(SETREN, value);
    }

    /**Gets the attribute value for the calculated attribute RenFob
     */
    public Boolean getRenFob() {
        return (Boolean) getAttributeInternal(RENFOB);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RenFob
     */
    public void setRenFob(Boolean value) {
        setAttributeInternal(RENFOB, value);
    }

    /**Gets the attribute value for the calculated attribute RenCif
     */
    public Boolean getRenCif() {
        return (Boolean) getAttributeInternal(RENCIF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RenCif
     */
    public void setRenCif(Boolean value) {
        setAttributeInternal(RENCIF, value);
    }

    /**Gets the attribute value for the calculated attribute PIRenFob
     */
    public Boolean getPIRenFob() {
        return (Boolean) getAttributeInternal(PIRENFOB);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PIRenFob
     */
    public void setPIRenFob(Boolean value) {
        setAttributeInternal(PIRENFOB, value);
    }

    /**Gets the attribute value for the calculated attribute PIRenCif
     */
    public Boolean getPIRenCif() {
        return (Boolean) getAttributeInternal(PIRENCIF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PIRenCif
     */
    public void setPIRenCif(Boolean value) {
        setAttributeInternal(PIRENCIF, value);
    }
}
