package oracle.apps.sfc.lcissuance.multi.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradeTermsVORowImpl extends OAViewRowImpl {

    public static final int TRADETERMS = 0;

    /**This is the default constructor (do not remove)
     */
    public TradeTermsVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Tradeterms
     */
    public String getTradeterms() {
        return (String) getAttributeInternal(TRADETERMS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tradeterms
     */
    public void setTradeterms(String value) {
        setAttributeInternal(TRADETERMS, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRADETERMS:
            return getTradeterms();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRADETERMS:
            setTradeterms((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
