package oracle.apps.sfc.lcissuance.multi.server;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LCReportEVODefImpl extends ViewDefImpl {
    public LCReportEVODefImpl(String name) {
        super(name);
    }

    /**This is the default constructor (do not remove)
     */
    public LCReportEVODefImpl() {
    }
}
