ALTER TABLE TRI2GPS_DEV.T_MIGRATION_DETAILS ADD DISABLE_SKIP VARCHAR2(50);
ALTER TABLE TRI2GPS_DEV.T_ISSUES_SOLUTION_OBJECTS_LOG ADD DISABLE_SKIP VARCHAR2(50);
ALTER TABLE TRI2GPS_DEV.T_MIGRATION_DETAILS_LOG ADD DISABLE_SKIP VARCHAR2(50);
commit;