package oracle.apps.sfc.lcissuance.multi.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VendorSiteVORowImpl extends OAViewRowImpl {
    public static final int VENDORID = 0;
    public static final int VENDORSITEID = 1;
    public static final int VENDORSITECODE = 2;
    public static final int LCCOUNTRYEXPIRE = 3;
    public static final int VENDORSITEADDR = 4;
    public static final int POCURRENCY = 5;
    public static final int LCCLASSIFICATION = 6;
    public static final int POHEADERID = 7;

    /**This is the default constructor (do not remove)
     */
    public VendorSiteVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute VendorSiteId
     */
    public Number getVendorSiteId() {
        return (Number) getAttributeInternal(VENDORSITEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteId
     */
    public void setVendorSiteId(Number value) {
        setAttributeInternal(VENDORSITEID, value);
    }

    /**Gets the attribute value for the calculated attribute VendorSiteCode
     */
    public String getVendorSiteCode() {
        return (String) getAttributeInternal(VENDORSITECODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteCode
     */
    public void setVendorSiteCode(String value) {
        setAttributeInternal(VENDORSITECODE, value);
    }

    /**Gets the attribute value for the calculated attribute VendorSiteAddr
     */
    public String getVendorSiteAddr() {
        return (String) getAttributeInternal(VENDORSITEADDR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteAddr
     */
    public void setVendorSiteAddr(String value) {
        setAttributeInternal(VENDORSITEADDR, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case VENDORID:
            return getVendorId();
        case VENDORSITEID:
            return getVendorSiteId();
        case VENDORSITECODE:
            return getVendorSiteCode();
        case LCCOUNTRYEXPIRE:
            return getLcCountryExpire();
        case VENDORSITEADDR:
            return getVendorSiteAddr();
        case POCURRENCY:
            return getPoCurrency();
        case LCCLASSIFICATION:
            return getLcClassification();
        case POHEADERID:
            return getPoHeaderId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case VENDORID:
            setVendorId((Number)value);
            return;
        case VENDORSITEID:
            setVendorSiteId((Number)value);
            return;
        case VENDORSITECODE:
            setVendorSiteCode((String)value);
            return;
        case LCCOUNTRYEXPIRE:
            setLcCountryExpire((String)value);
            return;
        case VENDORSITEADDR:
            setVendorSiteAddr((String)value);
            return;
        case POCURRENCY:
            setPoCurrency((String)value);
            return;
        case LCCLASSIFICATION:
            setLcClassification((String)value);
            return;
        case POHEADERID:
            setPoHeaderId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute VendorId
     */
    public Number getVendorId() {
        return (Number) getAttributeInternal(VENDORID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**Gets the attribute value for the calculated attribute PoCurrency
     */
    public String getPoCurrency() {
        return (String) getAttributeInternal(POCURRENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoCurrency
     */
    public void setPoCurrency(String value) {
        setAttributeInternal(POCURRENCY, value);
    }

    /**Gets the attribute value for the calculated attribute LcClassification
     */
    public String getLcClassification() {
        return (String) getAttributeInternal(LCCLASSIFICATION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcClassification
     */
    public void setLcClassification(String value) {
        setAttributeInternal(LCCLASSIFICATION, value);
    }

    /**Gets the attribute value for the calculated attribute LcCountryExpire
     */
    public String getLcCountryExpire() {
        return (String) getAttributeInternal(LCCOUNTRYEXPIRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcCountryExpire
     */
    public void setLcCountryExpire(String value) {
        setAttributeInternal(LCCOUNTRYEXPIRE, value);
    }

    /**Gets the attribute value for the calculated attribute PoHeaderId
     */
    public Number getPoHeaderId() {
        return (Number) getAttributeInternal(POHEADERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoHeaderId
     */
    public void setPoHeaderId(Number value) {
        setAttributeInternal(POHEADERID, value);
    }
}
