package oracle.apps.sfc.lcissuance.multi.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LCRequestHdrEOImpl extends OAEntityImpl {
    public static final int LCREQUESTID = 0;
    public static final int LCORGID = 1;
    public static final int VENDORID = 2;
    public static final int VENDORSITEID = 3;
    public static final int LCCURRENCYCODE = 4;
    public static final int LCVALUE = 5;
    public static final int LCCLASSIFICATION = 6;
    public static final int LCSTATUS = 7;
    public static final int LCDATE = 8;
    public static final int TOTALPOVALUE = 9;
    public static final int BANKID = 10;
    public static final int BANKNAME = 11;
    public static final int BANKADDRESS = 12;
    public static final int BANKIFSCSWIFTCODE = 13;
    public static final int BANKIBAN = 14;
    public static final int LCPARTIALSHIPMENT = 15;
    public static final int LCTRANSHIPMENT = 16;
    public static final int LCMODEOFTRANSPORT = 17;
    public static final int LCPERIODOFDOCUMENT = 18;
    public static final int LCCOUNTRYOFORIGIN = 19;
    public static final int LCCOUNTRYEXPIRE = 20;
    public static final int LCLASTDATEOFSHIPMENT = 21;
    public static final int LCEXPIRYDATE = 22;
    public static final int LCPORTOFDISCHARGE = 23;
    public static final int LCPORTOFLOADING = 24;
    public static final int LCPAYMENTTERMS = 25;
    public static final int LCTRADETERMS = 26;
    public static final int LCPAGEPOMODE = 27;
    public static final int TREASURYCOMMENTS = 28;
    public static final int SUPPLIERCOMMENTS = 29;
    public static final int COMMHEADCOMMENTS = 30;
    public static final int ORIGINALLCNO = 31;
    public static final int ATTRIBUTECATEGORY = 32;
    public static final int ATTRIBUTE1 = 33;
    public static final int ATTRIBUTE2 = 34;
    public static final int ATTRIBUTE3 = 35;
    public static final int ATTRIBUTE4 = 36;
    public static final int ATTRIBUTE5 = 37;
    public static final int ATTRIBUTE6 = 38;
    public static final int ATTRIBUTE7 = 39;
    public static final int ATTRIBUTE8 = 40;
    public static final int ATTRIBUTE9 = 41;
    public static final int ATTRIBUTE10 = 42;
    public static final int ATTRIBUTE11 = 43;
    public static final int ATTRIBUTE12 = 44;
    public static final int ATTRIBUTE13 = 45;
    public static final int ATTRIBUTE14 = 46;
    public static final int ATTRIBUTE15 = 47;
    public static final int CREATIONDATE = 48;
    public static final int CREATEDBY = 49;
    public static final int LASTUPDATEDATE = 50;
    public static final int LASTUPDATEDBY = 51;
    public static final int LASTUPDATELOGIN = 52;
    public static final int ROWID = 53;
    public static final int DESCOFGOODS = 54;
    public static final int LASTDATEOFSHIPPI = 55;
    public static final int TYPEOFLC = 56;
    public static final int FINANCECOMMENTS = 57;
    public static final int LCINCOTERM = 58;
    public static final int PIINCOTERM = 59;
    public static final int ATTRIBUTE25 = 60;
    public static final int ATTRIBUTE16 = 61;
    public static final int ATTRIBUTE17 = 62;
    public static final int ATTRIBUTE18 = 63;
    public static final int ATTRIBUTE19 = 64;
    public static final int ATTRIBUTE21 = 65;
    public static final int ATTRIBUTE20 = 66;
    public static final int ATTRIBUTE22 = 67;
    public static final int ATTRIBUTE23 = 68;
    public static final int ATTRIBUTE24 = 69;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public LCRequestHdrEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.sfc.lcissuance.multi.schema.server.LCRequestHdrEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for LcRequestId, using the alias name LcRequestId
     */
    public Number getLcRequestId() {
        return (Number)getAttributeInternal(LCREQUESTID);
    }

    /**Sets <code>value</code> as the attribute value for LcRequestId
     */
    public void setLcRequestId(Number value) {
        setAttributeInternal(LCREQUESTID, value);
    }

    /**Gets the attribute value for LcOrgId, using the alias name LcOrgId
     */
    public Number getLcOrgId() {
        return (Number)getAttributeInternal(LCORGID);
    }

    /**Sets <code>value</code> as the attribute value for LcOrgId
     */
    public void setLcOrgId(Number value) {
        setAttributeInternal(LCORGID, value);
    }

    /**Gets the attribute value for VendorId, using the alias name VendorId
     */
    public Number getVendorId() {
        return (Number)getAttributeInternal(VENDORID);
    }

    /**Sets <code>value</code> as the attribute value for VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**Gets the attribute value for VendorSiteId, using the alias name VendorSiteId
     */
    public Number getVendorSiteId() {
        return (Number)getAttributeInternal(VENDORSITEID);
    }

    /**Sets <code>value</code> as the attribute value for VendorSiteId
     */
    public void setVendorSiteId(Number value) {
        setAttributeInternal(VENDORSITEID, value);
    }

    /**Gets the attribute value for LcCurrencyCode, using the alias name LcCurrencyCode
     */
    public String getLcCurrencyCode() {
        return (String)getAttributeInternal(LCCURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for LcCurrencyCode
     */
    public void setLcCurrencyCode(String value) {
        setAttributeInternal(LCCURRENCYCODE, value);
    }

    /**Gets the attribute value for LcValue, using the alias name LcValue
     */
    public Number getLcValue() {
        return (Number)getAttributeInternal(LCVALUE);
    }

    /**Sets <code>value</code> as the attribute value for LcValue
     */
    public void setLcValue(Number value) {
        setAttributeInternal(LCVALUE, value);
    }

    /**Gets the attribute value for LcClassification, using the alias name LcClassification
     */
    public String getLcClassification() {
        return (String)getAttributeInternal(LCCLASSIFICATION);
    }

    /**Sets <code>value</code> as the attribute value for LcClassification
     */
    public void setLcClassification(String value) {
        setAttributeInternal(LCCLASSIFICATION, value);
    }

    /**Gets the attribute value for LcStatus, using the alias name LcStatus
     */
    public String getLcStatus() {
        return (String)getAttributeInternal(LCSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for LcStatus
     */
    public void setLcStatus(String value) {
        setAttributeInternal(LCSTATUS, value);
    }

    /**Gets the attribute value for LcDate, using the alias name LcDate
     */
    public Date getLcDate() {
        return (Date)getAttributeInternal(LCDATE);
    }

    /**Sets <code>value</code> as the attribute value for LcDate
     */
    public void setLcDate(Date value) {
        setAttributeInternal(LCDATE, value);
    }

    /**Gets the attribute value for TotalPoValue, using the alias name TotalPoValue
     */
    public Number getTotalPoValue() {
        return (Number)getAttributeInternal(TOTALPOVALUE);
    }

    /**Sets <code>value</code> as the attribute value for TotalPoValue
     */
    public void setTotalPoValue(Number value) {
        setAttributeInternal(TOTALPOVALUE, value);
    }

    /**Gets the attribute value for BankId, using the alias name BankId
     */
    public Number getBankId() {
        return (Number)getAttributeInternal(BANKID);
    }

    /**Sets <code>value</code> as the attribute value for BankId
     */
    public void setBankId(Number value) {
        setAttributeInternal(BANKID, value);
    }

    /**Gets the attribute value for BankName, using the alias name BankName
     */
    public String getBankName() {
        return (String)getAttributeInternal(BANKNAME);
    }

    /**Sets <code>value</code> as the attribute value for BankName
     */
    public void setBankName(String value) {
        setAttributeInternal(BANKNAME, value);
    }

    /**Gets the attribute value for BankAddress, using the alias name BankAddress
     */
    public String getBankAddress() {
        return (String)getAttributeInternal(BANKADDRESS);
    }

    /**Sets <code>value</code> as the attribute value for BankAddress
     */
    public void setBankAddress(String value) {
        setAttributeInternal(BANKADDRESS, value);
    }

    /**Gets the attribute value for BankIfscSwiftCode, using the alias name BankIfscSwiftCode
     */
    public String getBankIfscSwiftCode() {
        return (String)getAttributeInternal(BANKIFSCSWIFTCODE);
    }

    /**Sets <code>value</code> as the attribute value for BankIfscSwiftCode
     */
    public void setBankIfscSwiftCode(String value) {
        setAttributeInternal(BANKIFSCSWIFTCODE, value);
    }

    /**Gets the attribute value for BankIban, using the alias name BankIban
     */
    public String getBankIban() {
        return (String)getAttributeInternal(BANKIBAN);
    }

    /**Sets <code>value</code> as the attribute value for BankIban
     */
    public void setBankIban(String value) {
        setAttributeInternal(BANKIBAN, value);
    }

    /**Gets the attribute value for LcPartialShipment, using the alias name LcPartialShipment
     */
    public String getLcPartialShipment() {
        return (String)getAttributeInternal(LCPARTIALSHIPMENT);
    }

    /**Sets <code>value</code> as the attribute value for LcPartialShipment
     */
    public void setLcPartialShipment(String value) {
        setAttributeInternal(LCPARTIALSHIPMENT, value);
    }

    /**Gets the attribute value for LcTranshipment, using the alias name LcTranshipment
     */
    public String getLcTranshipment() {
        return (String)getAttributeInternal(LCTRANSHIPMENT);
    }

    /**Sets <code>value</code> as the attribute value for LcTranshipment
     */
    public void setLcTranshipment(String value) {
        setAttributeInternal(LCTRANSHIPMENT, value);
    }

    /**Gets the attribute value for LcModeOfTransport, using the alias name LcModeOfTransport
     */
    public String getLcModeOfTransport() {
        return (String)getAttributeInternal(LCMODEOFTRANSPORT);
    }

    /**Sets <code>value</code> as the attribute value for LcModeOfTransport
     */
    public void setLcModeOfTransport(String value) {
        setAttributeInternal(LCMODEOFTRANSPORT, value);
    }

    /**Gets the attribute value for LcPeriodOfDocument, using the alias name LcPeriodOfDocument
     */
    public String getLcPeriodOfDocument() {
        return (String)getAttributeInternal(LCPERIODOFDOCUMENT);
    }

    /**Sets <code>value</code> as the attribute value for LcPeriodOfDocument
     */
    public void setLcPeriodOfDocument(String value) {
        setAttributeInternal(LCPERIODOFDOCUMENT, value);
    }

    /**Gets the attribute value for LcCountryOfOrigin, using the alias name LcCountryOfOrigin
     */
    public String getLcCountryOfOrigin() {
        return (String)getAttributeInternal(LCCOUNTRYOFORIGIN);
    }

    /**Sets <code>value</code> as the attribute value for LcCountryOfOrigin
     */
    public void setLcCountryOfOrigin(String value) {
        setAttributeInternal(LCCOUNTRYOFORIGIN, value);
    }

    /**Gets the attribute value for LcCountryExpire, using the alias name LcCountryExpire
     */
    public String getLcCountryExpire() {
        return (String)getAttributeInternal(LCCOUNTRYEXPIRE);
    }

    /**Sets <code>value</code> as the attribute value for LcCountryExpire
     */
    public void setLcCountryExpire(String value) {
        setAttributeInternal(LCCOUNTRYEXPIRE, value);
    }

    /**Gets the attribute value for LcLastDateOfShipment, using the alias name LcLastDateOfShipment
     */
    public Date getLcLastDateOfShipment() {
        return (Date)getAttributeInternal(LCLASTDATEOFSHIPMENT);
    }

    /**Sets <code>value</code> as the attribute value for LcLastDateOfShipment
     */
    public void setLcLastDateOfShipment(Date value) {
        setAttributeInternal(LCLASTDATEOFSHIPMENT, value);
    }

    /**Gets the attribute value for LcExpiryDate, using the alias name LcExpiryDate
     */
    public Date getLcExpiryDate() {
        return (Date)getAttributeInternal(LCEXPIRYDATE);
    }

    /**Sets <code>value</code> as the attribute value for LcExpiryDate
     */
    public void setLcExpiryDate(Date value) {
        setAttributeInternal(LCEXPIRYDATE, value);
    }

    /**Gets the attribute value for LcPortOfDischarge, using the alias name LcPortOfDischarge
     */
    public String getLcPortOfDischarge() {
        return (String)getAttributeInternal(LCPORTOFDISCHARGE);
    }

    /**Sets <code>value</code> as the attribute value for LcPortOfDischarge
     */
    public void setLcPortOfDischarge(String value) {
        setAttributeInternal(LCPORTOFDISCHARGE, value);
    }

    /**Gets the attribute value for LcPortOfLoading, using the alias name LcPortOfLoading
     */
    public String getLcPortOfLoading() {
        return (String)getAttributeInternal(LCPORTOFLOADING);
    }

    /**Sets <code>value</code> as the attribute value for LcPortOfLoading
     */
    public void setLcPortOfLoading(String value) {
        setAttributeInternal(LCPORTOFLOADING, value);
    }

    /**Gets the attribute value for LcPaymentTerms, using the alias name LcPaymentTerms
     */
    public String getLcPaymentTerms() {
        return (String)getAttributeInternal(LCPAYMENTTERMS);
    }

    /**Sets <code>value</code> as the attribute value for LcPaymentTerms
     */
    public void setLcPaymentTerms(String value) {
        setAttributeInternal(LCPAYMENTTERMS, value);
    }

    /**Gets the attribute value for LcTradeTerms, using the alias name LcTradeTerms
     */
    public String getLcTradeTerms() {
        return (String)getAttributeInternal(LCTRADETERMS);
    }

    /**Sets <code>value</code> as the attribute value for LcTradeTerms
     */
    public void setLcTradeTerms(String value) {
        setAttributeInternal(LCTRADETERMS, value);
    }

    /**Gets the attribute value for LcPagePoMode, using the alias name LcPagePoMode
     */
    public String getLcPagePoMode() {
        return (String)getAttributeInternal(LCPAGEPOMODE);
    }

    /**Sets <code>value</code> as the attribute value for LcPagePoMode
     */
    public void setLcPagePoMode(String value) {
        setAttributeInternal(LCPAGEPOMODE, value);
    }

    /**Gets the attribute value for TreasuryComments, using the alias name TreasuryComments
     */
    public String getTreasuryComments() {
        return (String)getAttributeInternal(TREASURYCOMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for TreasuryComments
     */
    public void setTreasuryComments(String value) {
        setAttributeInternal(TREASURYCOMMENTS, value);
    }

    /**Gets the attribute value for SupplierComments, using the alias name SupplierComments
     */
    public String getSupplierComments() {
        return (String)getAttributeInternal(SUPPLIERCOMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for SupplierComments
     */
    public void setSupplierComments(String value) {
        setAttributeInternal(SUPPLIERCOMMENTS, value);
    }

    /**Gets the attribute value for CommheadComments, using the alias name CommheadComments
     */
    public String getCommheadComments() {
        return (String)getAttributeInternal(COMMHEADCOMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for CommheadComments
     */
    public void setCommheadComments(String value) {
        setAttributeInternal(COMMHEADCOMMENTS, value);
    }

    /**Gets the attribute value for OriginalLcNo, using the alias name OriginalLcNo
     */
    public String getOriginalLcNo() {
        return (String)getAttributeInternal(ORIGINALLCNO);
    }

    /**Sets <code>value</code> as the attribute value for OriginalLcNo
     */
    public void setOriginalLcNo(String value) {
        setAttributeInternal(ORIGINALLCNO, value);
    }

    /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for Attribute6, using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for Attribute7, using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for Attribute8, using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for Attribute9, using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for Attribute10, using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for Attribute11, using the alias name Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**Sets <code>value</code> as the attribute value for Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**Gets the attribute value for Attribute12, using the alias name Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**Sets <code>value</code> as the attribute value for Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**Gets the attribute value for Attribute13, using the alias name Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**Sets <code>value</code> as the attribute value for Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**Gets the attribute value for Attribute14, using the alias name Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**Sets <code>value</code> as the attribute value for Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**Gets the attribute value for Attribute15, using the alias name Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**Sets <code>value</code> as the attribute value for Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for RowID, using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LCREQUESTID:
            return getLcRequestId();
        case LCORGID:
            return getLcOrgId();
        case VENDORID:
            return getVendorId();
        case VENDORSITEID:
            return getVendorSiteId();
        case LCCURRENCYCODE:
            return getLcCurrencyCode();
        case LCVALUE:
            return getLcValue();
        case LCCLASSIFICATION:
            return getLcClassification();
        case LCSTATUS:
            return getLcStatus();
        case LCDATE:
            return getLcDate();
        case TOTALPOVALUE:
            return getTotalPoValue();
        case BANKID:
            return getBankId();
        case BANKNAME:
            return getBankName();
        case BANKADDRESS:
            return getBankAddress();
        case BANKIFSCSWIFTCODE:
            return getBankIfscSwiftCode();
        case BANKIBAN:
            return getBankIban();
        case LCPARTIALSHIPMENT:
            return getLcPartialShipment();
        case LCTRANSHIPMENT:
            return getLcTranshipment();
        case LCMODEOFTRANSPORT:
            return getLcModeOfTransport();
        case LCPERIODOFDOCUMENT:
            return getLcPeriodOfDocument();
        case LCCOUNTRYOFORIGIN:
            return getLcCountryOfOrigin();
        case LCCOUNTRYEXPIRE:
            return getLcCountryExpire();
        case LCLASTDATEOFSHIPMENT:
            return getLcLastDateOfShipment();
        case LCEXPIRYDATE:
            return getLcExpiryDate();
        case LCPORTOFDISCHARGE:
            return getLcPortOfDischarge();
        case LCPORTOFLOADING:
            return getLcPortOfLoading();
        case LCPAYMENTTERMS:
            return getLcPaymentTerms();
        case LCTRADETERMS:
            return getLcTradeTerms();
        case LCPAGEPOMODE:
            return getLcPagePoMode();
        case TREASURYCOMMENTS:
            return getTreasuryComments();
        case SUPPLIERCOMMENTS:
            return getSupplierComments();
        case COMMHEADCOMMENTS:
            return getCommheadComments();
        case ORIGINALLCNO:
            return getOriginalLcNo();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case ATTRIBUTE11:
            return getAttribute11();
        case ATTRIBUTE12:
            return getAttribute12();
        case ATTRIBUTE13:
            return getAttribute13();
        case ATTRIBUTE14:
            return getAttribute14();
        case ATTRIBUTE15:
            return getAttribute15();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ROWID:
            return getRowID();
        case DESCOFGOODS:
            return getDescOfGoods();
        case LASTDATEOFSHIPPI:
            return getLastDateOfShipPi();
        case TYPEOFLC:
            return getTypeOfLc();
        case FINANCECOMMENTS:
            return getFinanceComments();
        case LCINCOTERM:
            return getLcincoterm();
        case PIINCOTERM:
            return getPiincoterm();
        case ATTRIBUTE25:
            return getAttribute25();
        case ATTRIBUTE16:
            return getAttribute16();
        case ATTRIBUTE17:
            return getAttribute17();
        case ATTRIBUTE18:
            return getAttribute18();
        case ATTRIBUTE19:
            return getAttribute19();
        case ATTRIBUTE21:
            return getAttribute21();
        case ATTRIBUTE20:
            return getAttribute20();
        case ATTRIBUTE22:
            return getAttribute22();
        case ATTRIBUTE23:
            return getAttribute23();
        case ATTRIBUTE24:
            return getAttribute24();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LCREQUESTID:
            setLcRequestId((Number)value);
            return;
        case LCORGID:
            setLcOrgId((Number)value);
            return;
        case VENDORID:
            setVendorId((Number)value);
            return;
        case VENDORSITEID:
            setVendorSiteId((Number)value);
            return;
        case LCCURRENCYCODE:
            setLcCurrencyCode((String)value);
            return;
        case LCVALUE:
            setLcValue((Number)value);
            return;
        case LCCLASSIFICATION:
            setLcClassification((String)value);
            return;
        case LCSTATUS:
            setLcStatus((String)value);
            return;
        case LCDATE:
            setLcDate((Date)value);
            return;
        case TOTALPOVALUE:
            setTotalPoValue((Number)value);
            return;
        case BANKID:
            setBankId((Number)value);
            return;
        case BANKNAME:
            setBankName((String)value);
            return;
        case BANKADDRESS:
            setBankAddress((String)value);
            return;
        case BANKIFSCSWIFTCODE:
            setBankIfscSwiftCode((String)value);
            return;
        case BANKIBAN:
            setBankIban((String)value);
            return;
        case LCPARTIALSHIPMENT:
            setLcPartialShipment((String)value);
            return;
        case LCTRANSHIPMENT:
            setLcTranshipment((String)value);
            return;
        case LCMODEOFTRANSPORT:
            setLcModeOfTransport((String)value);
            return;
        case LCPERIODOFDOCUMENT:
            setLcPeriodOfDocument((String)value);
            return;
        case LCCOUNTRYOFORIGIN:
            setLcCountryOfOrigin((String)value);
            return;
        case LCCOUNTRYEXPIRE:
            setLcCountryExpire((String)value);
            return;
        case LCLASTDATEOFSHIPMENT:
            setLcLastDateOfShipment((Date)value);
            return;
        case LCEXPIRYDATE:
            setLcExpiryDate((Date)value);
            return;
        case LCPORTOFDISCHARGE:
            setLcPortOfDischarge((String)value);
            return;
        case LCPORTOFLOADING:
            setLcPortOfLoading((String)value);
            return;
        case LCPAYMENTTERMS:
            setLcPaymentTerms((String)value);
            return;
        case LCTRADETERMS:
            setLcTradeTerms((String)value);
            return;
        case LCPAGEPOMODE:
            setLcPagePoMode((String)value);
            return;
        case TREASURYCOMMENTS:
            setTreasuryComments((String)value);
            return;
        case SUPPLIERCOMMENTS:
            setSupplierComments((String)value);
            return;
        case COMMHEADCOMMENTS:
            setCommheadComments((String)value);
            return;
        case ORIGINALLCNO:
            setOriginalLcNo((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case ATTRIBUTE11:
            setAttribute11((String)value);
            return;
        case ATTRIBUTE12:
            setAttribute12((String)value);
            return;
        case ATTRIBUTE13:
            setAttribute13((String)value);
            return;
        case ATTRIBUTE14:
            setAttribute14((String)value);
            return;
        case ATTRIBUTE15:
            setAttribute15((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case DESCOFGOODS:
            setDescOfGoods((String)value);
            return;
        case LASTDATEOFSHIPPI:
            setLastDateOfShipPi((Date)value);
            return;
        case TYPEOFLC:
            setTypeOfLc((String)value);
            return;
        case FINANCECOMMENTS:
            setFinanceComments((String)value);
            return;
        case LCINCOTERM:
            setLcincoterm((String)value);
            return;
        case PIINCOTERM:
            setPiincoterm((String)value);
            return;
        case ATTRIBUTE25:
            setAttribute25((String)value);
            return;
        case ATTRIBUTE16:
            setAttribute16((String)value);
            return;
        case ATTRIBUTE17:
            setAttribute17((String)value);
            return;
        case ATTRIBUTE18:
            setAttribute18((String)value);
            return;
        case ATTRIBUTE19:
            setAttribute19((String)value);
            return;
        case ATTRIBUTE21:
            setAttribute21((String)value);
            return;
        case ATTRIBUTE20:
            setAttribute20((String)value);
            return;
        case ATTRIBUTE22:
            setAttribute22((String)value);
            return;
        case ATTRIBUTE23:
            setAttribute23((String)value);
            return;
        case ATTRIBUTE24:
            setAttribute24((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for DescOfGoods, using the alias name DescOfGoods
     */
    public String getDescOfGoods() {
        return (String)getAttributeInternal(DESCOFGOODS);
    }

    /**Sets <code>value</code> as the attribute value for DescOfGoods
     */
    public void setDescOfGoods(String value) {
        setAttributeInternal(DESCOFGOODS, value);
    }

    /**Gets the attribute value for LastDateOfShipPi, using the alias name LastDateOfShipPi
     */
    public Date getLastDateOfShipPi() {
        return (Date)getAttributeInternal(LASTDATEOFSHIPPI);
    }

    /**Sets <code>value</code> as the attribute value for LastDateOfShipPi
     */
    public void setLastDateOfShipPi(Date value) {
        setAttributeInternal(LASTDATEOFSHIPPI, value);
    }

    /**Gets the attribute value for TypeOfLc, using the alias name TypeOfLc
     */
    public String getTypeOfLc() {
        return (String)getAttributeInternal(TYPEOFLC);
    }

    /**Sets <code>value</code> as the attribute value for TypeOfLc
     */
    public void setTypeOfLc(String value) {
        setAttributeInternal(TYPEOFLC, value);
    }

    /**Gets the attribute value for FinanceComments, using the alias name FinanceComments
     */
    public String getFinanceComments() {
        return (String)getAttributeInternal(FINANCECOMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for FinanceComments
     */
    public void setFinanceComments(String value) {
        setAttributeInternal(FINANCECOMMENTS, value);
    }

    /**Gets the attribute value for Lcincoterm, using the alias name Lcincoterm
     */
    public String getLcincoterm() {
        return (String)getAttributeInternal(LCINCOTERM);
    }

    /**Sets <code>value</code> as the attribute value for Lcincoterm
     */
    public void setLcincoterm(String value) {
        setAttributeInternal(LCINCOTERM, value);
    }

    /**Gets the attribute value for Piincoterm, using the alias name Piincoterm
     */
    public String getPiincoterm() {
        return (String)getAttributeInternal(PIINCOTERM);
    }

    /**Sets <code>value</code> as the attribute value for Piincoterm
     */
    public void setPiincoterm(String value) {
        setAttributeInternal(PIINCOTERM, value);
    }

    /**Gets the attribute value for Attribute25, using the alias name Attribute25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**Sets <code>value</code> as the attribute value for Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**Gets the attribute value for Attribute16, using the alias name Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**Sets <code>value</code> as the attribute value for Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**Gets the attribute value for Attribute17, using the alias name Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**Sets <code>value</code> as the attribute value for Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**Gets the attribute value for Attribute18, using the alias name Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**Sets <code>value</code> as the attribute value for Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**Gets the attribute value for Attribute19, using the alias name Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**Sets <code>value</code> as the attribute value for Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**Gets the attribute value for Attribute21, using the alias name Attribute21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**Sets <code>value</code> as the attribute value for Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**Gets the attribute value for Attribute20, using the alias name Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**Sets <code>value</code> as the attribute value for Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**Gets the attribute value for Attribute22, using the alias name Attribute22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**Sets <code>value</code> as the attribute value for Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**Gets the attribute value for Attribute23, using the alias name Attribute23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**Sets <code>value</code> as the attribute value for Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**Gets the attribute value for Attribute24, using the alias name Attribute24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**Sets <code>value</code> as the attribute value for Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }
}
