package oracle.apps.sfc.lcissuance.multi.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LCReportEOImpl extends OAEntityImpl {
    public static final int LCREPID = 0;
    public static final int BANKREFNUMBER = 1;
    public static final int ACCEPTANCEVALUE = 2;
    public static final int AMOUNTININR = 3;
    public static final int DUEDATE = 4;
    public static final int ACCEPTANCEDATE = 5;
    public static final int SHIPMENTDATE = 6;
    public static final int SOURCEOFFUNDS = 7;
    public static final int EXCHANGERATE = 8;
    public static final int EXCHANGEDATE = 9;
    public static final int MARGINVALUE = 10;
    public static final int LCCOMMISSION = 11;
    public static final int OTHERCHARGES = 12;
    public static final int ESTIMATEDPAYMENTDATE = 13;
    public static final int TLPROJECTNAME = 14;
    public static final int LCSTATUS = 15;
    public static final int ATTRIBUTECATEGORY = 16;
    public static final int ATTRIBUTE1 = 17;
    public static final int ATTRIBUTE2 = 18;
    public static final int ATTRIBUTE3 = 19;
    public static final int ATTRIBUTE4 = 20;
    public static final int ATTRIBUTE5 = 21;
    public static final int ATTRIBUTE6 = 22;
    public static final int ATTRIBUTE7 = 23;
    public static final int ATTRIBUTE8 = 24;
    public static final int ATTRIBUTE9 = 25;
    public static final int ATTRIBUTE10 = 26;
    public static final int ATTRIBUTE11 = 27;
    public static final int ATTRIBUTE12 = 28;
    public static final int ATTRIBUTE13 = 29;
    public static final int ATTRIBUTE14 = 30;
    public static final int ATTRIBUTE15 = 31;
    public static final int ATTRIBUTE16 = 32;
    public static final int ATTRIBUTE17 = 33;
    public static final int ATTRIBUTE18 = 34;
    public static final int ATTRIBUTE19 = 35;
    public static final int ATTRIBUTE20 = 36;
    public static final int ATTRIBUTE21 = 37;
    public static final int ATTRIBUTE22 = 38;
    public static final int ATTRIBUTE23 = 39;
    public static final int ATTRIBUTE24 = 40;
    public static final int ATTRIBUTE25 = 41;
    public static final int CREATIONDATE = 42;
    public static final int CREATEDBY = 43;
    public static final int LASTUPDATEDATE = 44;
    public static final int LASTUPDATEDBY = 45;
    public static final int LASTUPDATELOGIN = 46;
    public static final int ROWID = 47;
    public static final int LCREQUESTID = 48;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public LCReportEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.sfc.lcissuance.multi.schema.server.LCReportEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for LcRepId, using the alias name LcRepId
     */
    public Number getLcRepId() {
        return (Number)getAttributeInternal(LCREPID);
    }

    /**Sets <code>value</code> as the attribute value for LcRepId
     */
    public void setLcRepId(Number value) {
        setAttributeInternal(LCREPID, value);
    }

    /**Gets the attribute value for BankRefNumber, using the alias name BankRefNumber
     */
    public String getBankRefNumber() {
        return (String)getAttributeInternal(BANKREFNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for BankRefNumber
     */
    public void setBankRefNumber(String value) {
        setAttributeInternal(BANKREFNUMBER, value);
    }

    /**Gets the attribute value for AcceptanceValue, using the alias name AcceptanceValue
     */
    public Number getAcceptanceValue() {
        return (Number)getAttributeInternal(ACCEPTANCEVALUE);
    }

    /**Sets <code>value</code> as the attribute value for AcceptanceValue
     */
    public void setAcceptanceValue(Number value) {
        setAttributeInternal(ACCEPTANCEVALUE, value);
    }

    /**Gets the attribute value for AmountInInr, using the alias name AmountInInr
     */
    public Number getAmountInInr() {
        return (Number)getAttributeInternal(AMOUNTININR);
    }

    /**Sets <code>value</code> as the attribute value for AmountInInr
     */
    public void setAmountInInr(Number value) {
        setAttributeInternal(AMOUNTININR, value);
    }

    /**Gets the attribute value for DueDate, using the alias name DueDate
     */
    public Date getDueDate() {
        return (Date)getAttributeInternal(DUEDATE);
    }

    /**Sets <code>value</code> as the attribute value for DueDate
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**Gets the attribute value for AcceptanceDate, using the alias name AcceptanceDate
     */
    public Date getAcceptanceDate() {
        return (Date)getAttributeInternal(ACCEPTANCEDATE);
    }

    /**Sets <code>value</code> as the attribute value for AcceptanceDate
     */
    public void setAcceptanceDate(Date value) {
        setAttributeInternal(ACCEPTANCEDATE, value);
    }

    /**Gets the attribute value for ShipmentDate, using the alias name ShipmentDate
     */
    public Date getShipmentDate() {
        return (Date)getAttributeInternal(SHIPMENTDATE);
    }

    /**Sets <code>value</code> as the attribute value for ShipmentDate
     */
    public void setShipmentDate(Date value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**Gets the attribute value for SourceOfFunds, using the alias name SourceOfFunds
     */
    public String getSourceOfFunds() {
        return (String)getAttributeInternal(SOURCEOFFUNDS);
    }

    /**Sets <code>value</code> as the attribute value for SourceOfFunds
     */
    public void setSourceOfFunds(String value) {
        setAttributeInternal(SOURCEOFFUNDS, value);
    }

    /**Gets the attribute value for ExchangeRate, using the alias name ExchangeRate
     */
    public Number getExchangeRate() {
        return (Number)getAttributeInternal(EXCHANGERATE);
    }

    /**Sets <code>value</code> as the attribute value for ExchangeRate
     */
    public void setExchangeRate(Number value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**Gets the attribute value for ExchangeDate, using the alias name ExchangeDate
     */
    public Date getExchangeDate() {
        return (Date)getAttributeInternal(EXCHANGEDATE);
    }

    /**Sets <code>value</code> as the attribute value for ExchangeDate
     */
    public void setExchangeDate(Date value) {
        setAttributeInternal(EXCHANGEDATE, value);
    }

    /**Gets the attribute value for MarginValue, using the alias name MarginValue
     */
    public Number getMarginValue() {
        return (Number)getAttributeInternal(MARGINVALUE);
    }

    /**Sets <code>value</code> as the attribute value for MarginValue
     */
    public void setMarginValue(Number value) {
        setAttributeInternal(MARGINVALUE, value);
    }

    /**Gets the attribute value for LcCommission, using the alias name LcCommission
     */
    public Number getLcCommission() {
        return (Number)getAttributeInternal(LCCOMMISSION);
    }

    /**Sets <code>value</code> as the attribute value for LcCommission
     */
    public void setLcCommission(Number value) {
        setAttributeInternal(LCCOMMISSION, value);
    }

    /**Gets the attribute value for OtherCharges, using the alias name OtherCharges
     */
    public Number getOtherCharges() {
        return (Number)getAttributeInternal(OTHERCHARGES);
    }

    /**Sets <code>value</code> as the attribute value for OtherCharges
     */
    public void setOtherCharges(Number value) {
        setAttributeInternal(OTHERCHARGES, value);
    }

    /**Gets the attribute value for EstimatedPaymentDate, using the alias name EstimatedPaymentDate
     */
    public Date getEstimatedPaymentDate() {
        return (Date)getAttributeInternal(ESTIMATEDPAYMENTDATE);
    }

    /**Sets <code>value</code> as the attribute value for EstimatedPaymentDate
     */
    public void setEstimatedPaymentDate(Date value) {
        setAttributeInternal(ESTIMATEDPAYMENTDATE, value);
    }

    /**Gets the attribute value for TlProjectName, using the alias name TlProjectName
     */
    public String getTlProjectName() {
        return (String)getAttributeInternal(TLPROJECTNAME);
    }

    /**Sets <code>value</code> as the attribute value for TlProjectName
     */
    public void setTlProjectName(String value) {
        setAttributeInternal(TLPROJECTNAME, value);
    }

    /**Gets the attribute value for LcStatus, using the alias name LcStatus
     */
    public String getLcStatus() {
        return (String)getAttributeInternal(LCSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for LcStatus
     */
    public void setLcStatus(String value) {
        setAttributeInternal(LCSTATUS, value);
    }

    /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for Attribute6, using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for Attribute7, using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for Attribute8, using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for Attribute9, using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for Attribute10, using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for Attribute11, using the alias name Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**Sets <code>value</code> as the attribute value for Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**Gets the attribute value for Attribute12, using the alias name Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**Sets <code>value</code> as the attribute value for Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**Gets the attribute value for Attribute13, using the alias name Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**Sets <code>value</code> as the attribute value for Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**Gets the attribute value for Attribute14, using the alias name Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**Sets <code>value</code> as the attribute value for Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**Gets the attribute value for Attribute15, using the alias name Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**Sets <code>value</code> as the attribute value for Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**Gets the attribute value for Attribute16, using the alias name Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**Sets <code>value</code> as the attribute value for Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**Gets the attribute value for Attribute17, using the alias name Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**Sets <code>value</code> as the attribute value for Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**Gets the attribute value for Attribute18, using the alias name Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**Sets <code>value</code> as the attribute value for Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**Gets the attribute value for Attribute19, using the alias name Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**Sets <code>value</code> as the attribute value for Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**Gets the attribute value for Attribute20, using the alias name Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**Sets <code>value</code> as the attribute value for Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**Gets the attribute value for Attribute21, using the alias name Attribute21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**Sets <code>value</code> as the attribute value for Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**Gets the attribute value for Attribute22, using the alias name Attribute22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**Sets <code>value</code> as the attribute value for Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**Gets the attribute value for Attribute23, using the alias name Attribute23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**Sets <code>value</code> as the attribute value for Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**Gets the attribute value for Attribute24, using the alias name Attribute24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**Sets <code>value</code> as the attribute value for Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**Gets the attribute value for Attribute25, using the alias name Attribute25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**Sets <code>value</code> as the attribute value for Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for RowID, using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LCREPID:
            return getLcRepId();
        case BANKREFNUMBER:
            return getBankRefNumber();
        case ACCEPTANCEVALUE:
            return getAcceptanceValue();
        case AMOUNTININR:
            return getAmountInInr();
        case DUEDATE:
            return getDueDate();
        case ACCEPTANCEDATE:
            return getAcceptanceDate();
        case SHIPMENTDATE:
            return getShipmentDate();
        case SOURCEOFFUNDS:
            return getSourceOfFunds();
        case EXCHANGERATE:
            return getExchangeRate();
        case EXCHANGEDATE:
            return getExchangeDate();
        case MARGINVALUE:
            return getMarginValue();
        case LCCOMMISSION:
            return getLcCommission();
        case OTHERCHARGES:
            return getOtherCharges();
        case ESTIMATEDPAYMENTDATE:
            return getEstimatedPaymentDate();
        case TLPROJECTNAME:
            return getTlProjectName();
        case LCSTATUS:
            return getLcStatus();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case ATTRIBUTE11:
            return getAttribute11();
        case ATTRIBUTE12:
            return getAttribute12();
        case ATTRIBUTE13:
            return getAttribute13();
        case ATTRIBUTE14:
            return getAttribute14();
        case ATTRIBUTE15:
            return getAttribute15();
        case ATTRIBUTE16:
            return getAttribute16();
        case ATTRIBUTE17:
            return getAttribute17();
        case ATTRIBUTE18:
            return getAttribute18();
        case ATTRIBUTE19:
            return getAttribute19();
        case ATTRIBUTE20:
            return getAttribute20();
        case ATTRIBUTE21:
            return getAttribute21();
        case ATTRIBUTE22:
            return getAttribute22();
        case ATTRIBUTE23:
            return getAttribute23();
        case ATTRIBUTE24:
            return getAttribute24();
        case ATTRIBUTE25:
            return getAttribute25();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ROWID:
            return getRowID();
        case LCREQUESTID:
            return getLcRequestId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LCREPID:
            setLcRepId((Number)value);
            return;
        case BANKREFNUMBER:
            setBankRefNumber((String)value);
            return;
        case ACCEPTANCEVALUE:
            setAcceptanceValue((Number)value);
            return;
        case AMOUNTININR:
            setAmountInInr((Number)value);
            return;
        case DUEDATE:
            setDueDate((Date)value);
            return;
        case ACCEPTANCEDATE:
            setAcceptanceDate((Date)value);
            return;
        case SHIPMENTDATE:
            setShipmentDate((Date)value);
            return;
        case SOURCEOFFUNDS:
            setSourceOfFunds((String)value);
            return;
        case EXCHANGERATE:
            setExchangeRate((Number)value);
            return;
        case EXCHANGEDATE:
            setExchangeDate((Date)value);
            return;
        case MARGINVALUE:
            setMarginValue((Number)value);
            return;
        case LCCOMMISSION:
            setLcCommission((Number)value);
            return;
        case OTHERCHARGES:
            setOtherCharges((Number)value);
            return;
        case ESTIMATEDPAYMENTDATE:
            setEstimatedPaymentDate((Date)value);
            return;
        case TLPROJECTNAME:
            setTlProjectName((String)value);
            return;
        case LCSTATUS:
            setLcStatus((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case ATTRIBUTE11:
            setAttribute11((String)value);
            return;
        case ATTRIBUTE12:
            setAttribute12((String)value);
            return;
        case ATTRIBUTE13:
            setAttribute13((String)value);
            return;
        case ATTRIBUTE14:
            setAttribute14((String)value);
            return;
        case ATTRIBUTE15:
            setAttribute15((String)value);
            return;
        case ATTRIBUTE16:
            setAttribute16((String)value);
            return;
        case ATTRIBUTE17:
            setAttribute17((String)value);
            return;
        case ATTRIBUTE18:
            setAttribute18((String)value);
            return;
        case ATTRIBUTE19:
            setAttribute19((String)value);
            return;
        case ATTRIBUTE20:
            setAttribute20((String)value);
            return;
        case ATTRIBUTE21:
            setAttribute21((String)value);
            return;
        case ATTRIBUTE22:
            setAttribute22((String)value);
            return;
        case ATTRIBUTE23:
            setAttribute23((String)value);
            return;
        case ATTRIBUTE24:
            setAttribute24((String)value);
            return;
        case ATTRIBUTE25:
            setAttribute25((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case LCREQUESTID:
            setLcRequestId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for LcRequestId, using the alias name LcRequestId
     */
    public Number getLcRequestId() {
        return (Number)getAttributeInternal(LCREQUESTID);
    }

    /**Sets <code>value</code> as the attribute value for LcRequestId
     */
    public void setLcRequestId(Number value) {
        setAttributeInternal(LCREQUESTID, value);
    }
}
