package oracle.apps.sfc.lcissuance.multi.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LCRevHistVORowImpl extends OAViewRowImpl {
    public static final int LCREQUESTID = 0;
    public static final int ATTRIBUTE9 = 1;
    public static final int REVISIONDATE = 2;
    public static final int SNO = 3;

    /**This is the default constructor (do not remove)
     */
    public LCRevHistVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute LcRequestId
     */
    public Number getLcRequestId() {
        return (Number) getAttributeInternal(LCREQUESTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LcRequestId
     */
    public void setLcRequestId(Number value) {
        setAttributeInternal(LCREQUESTID, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for the calculated attribute RevisionDate
     */
    public Date getRevisionDate() {
        return (Date) getAttributeInternal(REVISIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RevisionDate
     */
    public void setRevisionDate(Date value) {
        setAttributeInternal(REVISIONDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LCREQUESTID:
            return getLcRequestId();
        case ATTRIBUTE9:
            return getAttribute9();
        case REVISIONDATE:
            return getRevisionDate();
        case SNO:
            return getSNo();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LCREQUESTID:
            setLcRequestId((Number)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case REVISIONDATE:
            setRevisionDate((Date)value);
            return;
        case SNO:
            setSNo((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute SNo
     */
    public Number getSNo() {
        return (Number) getAttributeInternal(SNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SNo
     */
    public void setSNo(Number value) {
        setAttributeInternal(SNO, value);
    }
}
